name: snowpark_0110
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - defaults
dependencies:
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py38haa95532_0
  - libffi=3.4.2=hd77b12b_6
  - openssl=1.1.1t=h2bbff1b_0
  - pip=23.0.1=py38haa95532_0
  - python=3.8.16=h6244533_3
  - setuptools=65.6.3=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - pip:
    - altair==4.2.2
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asn1crypto==1.5.1
    - asttokens==2.2.1
    - attrs==23.1.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - blinker==1.6.2
    - cachetools==5.3.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.0.4
    - cloudpickle==2.0.0
    - colorama==0.4.6
    - comm==0.1.3
    - cryptography==40.0.2
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - filelock==3.12.0
    - fonttools==4.39.3
    - fqdn==1.5.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - holidays==0.29
    - idna==3.4
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - ipykernel==6.22.0
    - ipython==8.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.2.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - lightgbm==3.3.5
    - markupsafe==2.1.2
    - matplotlib==3.5.0
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - nbclassic==0.5.5
    - nbclient==0.7.3
    - nbconvert==7.3.1
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - notebook==6.5.4
    - notebook-shim==0.2.2
    - numpy==1.22.4
    - oscrypto==1.3.0
    - packaging==23.1
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - patsy==0.5.3
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.2.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==3.20.0
    - psutil==5.9.5
    - pure-eval==0.2.2
    - pyarrow==10.0.1
    - pycparser==2.21
    - pycryptodomex==3.17
    - pydeck==0.8.1b0
    - pygments==2.15.1
    - pyjwt==2.6.0
    - pympler==1.0.1
    - pyopenssl==23.1.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-tabnet==3.1.1
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywin32==306
    - pywinpty==2.0.10
    - pyyaml==6.0
    - pyzmq==25.0.2
    - qtconsole==5.4.2
    - qtpy==2.3.1
    - requests==2.28.2
    - rexmex==0.1.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.0.2
    - scipy==1.7.1
    - seaborn==0.11.2
    - semver==3.0.0
    - send2trash==1.8.0
    - setuptools-scm==7.1.0
    - six==1.16.0
    - sklearn==0.0.post4
    - smmap==5.0.0
    - sniffio==1.3.0
    - snowflake-connector-python==3.0.3
    - snowflake-snowpark-python==0.11.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - statsmodels==0.13.0
    - streamlit==1.8.1
    - tabulate==0.9.0
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.10.2
    - tornado==6.3.1
    - tqdm==4.65.0
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - tzlocal==4.3
    - uri-template==1.2.0
    - urllib3==1.26.15
    - validators==0.20.0
    - watchdog==3.0.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.7
    - xgboost==1.7.5
    - zipp==3.15.0
